### PR TITLE
[CMake] Opposing Force define + minor fixes for the sniper rifle

### PR DESCRIPTION
**Pull request by JoelTroch**
This PR add a CMake define called `USE_OPFOR`. If true, the Sniper Rifle and ropes (and it's electric wire variant) are enabled. The main purpose of this define is to give the modder the choice between Half-Life or Opposing Force as a base.

This PR also add some minor fixes for the sniper rifle, client prediction of it's ammo and tabulation are the major changes.

If this PR is accepted, I'll make another one for "HLEnhanced-Game" which provide a "Half-Life" base rather than an "Opposing Force" one that could be merged into a "valve" or "hl" branch.

### CODE REVIEW

**Comment by SamVanheer** [comment]
Your changes all look good, i'm only worried about the HUD slots number being tied to Opposing Force. Opposing Force has an extra 2 slots, but i added another 3 to increase it to 10. Maybe make this be controlled by something else?

**Comment by JoelTroch** [comment]
What about keeping the max slots limit to 10 but render to the last bucket only if there is a weapon in there ? Let's imagine that I have the Crowbar, Glock, Python, MP5, Shotgun and Crossbow, it would look like this:

Now let's say that I pick up some grenades, the HUD would look like that:


I hope you understand what I meant, not easy to describe with words ^^

**Comment by SamVanheer** [comment]
I understand it perfectly. It's a great idea, should it be implemented in the PR or after it's been merged in?

**Comment by JoelTroch** [comment]
For clarity purposes, it would be good that this comes in another PR ^^

**Comment by SamVanheer** [comment]
Alright, i'll merge this in then.

**Pull request merged**
